### ISSUE TITLE
Getting stuck on Verifying vmnet devices are healthy...

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/basebox#7]
when doing vagrant up, it get stuck on 

`==> default: Verifying vmnet devices are healthy...`

The temporary solution to fix this is, to restart the host and try again.

**Comment by d34dman** [comment]
btw, clearing `/etc/exports` and doing `sudo nfsd restart` didn't fix the problem.

**Comment by stmh** [comment]
any chance you are running virtual box and vmware simultaneously?

**Comment by d34dman** [comment]
oh yes! i used to run them. Next time it happens i will check if it is so.
